### PR TITLE
Add indentation to values with multiline strings

### LINKED ISSUE #21: Handle interpolations properly
```ts
import dedent from 'ts-dedent'

const fieldDocs = dedent`
  * a
  * b
  * c
`

const a = dedent`
  /**
   ${fieldIntro()}
   *
   ${fieldDocs}
   *
   ${fieldExample()} 
   */
`

function fieldIntro() {
  return dedent`
    * 0
  `
}
function fieldExample() {
  return dedent`
    * d
  `
}

console.log(a)

```
Expected
```
/**
 * 0
 *
 * a
 * b
 * c
 *
 * d 
 */
```

Actual

```
/**
 * 0
 *
 * a
* b
* c
 *
 * d 
 */
```

### PR DESCRIPTION
**Pull request by Whoaa512**
Includes test

Fixes #21

### CODE REVIEW

**Comment by Whoaa512** [comment]
Friendly bump @tamino-martinius

**Comment by tamino-martinius** [comment]
Thanks for the friendly bump and thanks even more for preparing this fix 🙏  
I'm currently on travel and will include your PR early next week @Whoaa512

**Comment by Whoaa512** [comment]
Thanks! I've just found a new bug with it so I'll try to get that patched before you look at it next week

**Comment by Whoaa512** [comment]
Unfortunately I couldn't find an easy way to fix the function call syntax so I left the failing test as skipped. I think fixing it for the tagged literal is additive at the very least. Let me know what you think

**Comment by tamino-martinius** [comment]
Thanks again @Whoaa512 and sorry for the delay

**Pull request merged**
